name: 'Setup HBX UniApp Builder'
description: 'Install HBuilderX core and build a UniApp (Vite) project for app-plus.'
author: 'Codex'
inputs:
  core_version:
    description: 'HBuilderX core version or archive name (e.g. 4.86, core-4.15.0.tar.gz).'
    required: false
    default: '4.86'
  uni_project_dir:
    description: 'Path to the UniApp project inside the workflow workspace.'
    required: false
    default: '.'
  output_dir:
    description: 'Directory to store the Uni build output (relative or absolute).'
    required: false
    default: 'result'
  node_env:
    description: 'Value for UNI_NODE_ENV.'
    required: false
    default: 'production'
outputs:
  output-dir:
    description: 'Absolute path to the build output directory.'
    value: ${{ steps.resolve-paths.outputs.output }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Resolve project and output paths
      id: resolve-paths
      shell: bash
      env:
        UNI_PROJECT_DIR: ${{ inputs.uni_project_dir }}
        UNI_OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        set -euo pipefail
        WORKSPACE="${GITHUB_WORKSPACE:-$PWD}"
        PROJECT="$UNI_PROJECT_DIR"
        if [[ ! "$PROJECT" = /* ]]; then
          PROJECT="$WORKSPACE/$PROJECT"
        fi
        if [[ ! -d "$PROJECT" ]]; then
          echo "Project directory '$PROJECT' does not exist." >&2
          exit 1
        fi
        OUTPUT="$UNI_OUTPUT_DIR"
        if [[ ! "$OUTPUT" = /* ]]; then
          OUTPUT="$WORKSPACE/$OUTPUT"
        fi
        mkdir -p "$OUTPUT"
        echo "project=$PROJECT" >> "$GITHUB_OUTPUT"
        echo "output=$OUTPUT" >> "$GITHUB_OUTPUT"
    - name: Extract HBuilderX core
      id: extract-core
      shell: bash
      run: |
        set -euo pipefail
        ARCHIVE_URL="https://github.com/golezi/uni_modules/releases/download/HBuilderX.4.85.2025110510/HBuilderX.4.85.2025110510.linux_x64.full.tar.gz"
        ACTION_PATH="${GITHUB_ACTION_PATH:-$PWD}"
        TMP_ARCHIVE="$(mktemp)"
        curl -fL "$ARCHIVE_URL" -o "$TMP_ARCHIVE"
        rm -rf "$HOME/HBuilderX"
        tar -xzf "$TMP_ARCHIVE" -C "$HOME"
        rm -f "$TMP_ARCHIVE"
        if [[ ! -d "$HOME/HBuilderX" ]]; then
          echo "Extraction failed: '$HOME/HBuilderX' not found." >&2
          exit 1
        fi
        if [[ ! -d "$ACTION_PATH/plugins" ]]; then
          echo "plugins directory not found in '$ACTION_PATH'." >&2
          exit 1
        fi
        mkdir -p "$HOME/HBuilderX/plugins"
        cp -a "$ACTION_PATH/plugins/." "$HOME/HBuilderX/plugins/"
        echo "core-root=$HOME/HBuilderX" >> "$GITHUB_OUTPUT"
